// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectListing.DataFile;

namespace ProjectListing.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210812065711_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectListing.DataFile.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Continent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BZ",
                            Continent = "North America",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AU",
                            Continent = "Oceania",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ES",
                            Continent = "Europe",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 4,
                            Code = "JP",
                            Continent = "	Asia",
                            Name = "Japan"
                        });
                });

            modelBuilder.Entity("ProjectListing.DataFile.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "383 Langosh Creek Toledo, Belize",
                            CountryId = 1,
                            Name = "Spring Mansion Hotel",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 2,
                            Address = "49409 Weimann Harbors, Australia",
                            CountryId = 2,
                            Name = "Majestic Star Resort & Spa",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "39452 Hintz Stravenue, Spain",
                            CountryId = 3,
                            Name = "Parallel Season Resort",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Address = "1428 Hills Village, Japan",
                            CountryId = 4,
                            Name = "Antique Mountain Motel",
                            Rating = 3.7999999999999998
                        });
                });

            modelBuilder.Entity("ProjectListing.DataFile.Hotel", b =>
                {
                    b.HasOne("ProjectListing.DataFile.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
